version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: df_postgres
    restart: always
    environment:
      - POSTGRES_USER=forge_user
      - POSTGRES_PASSWORD=forge_pass
      - POSTGRES_DB=Demiurge_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"     # troca p/ "5434:5432" se 5433 estiver ocupada
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks: [internal]

#  redis:
#    image: redis:7-alpine
#    container_name: df_redis
#    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 3s
#      retries: 5
#    networks: [internal]

#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: df_qdrant
#    restart: unless-stopped
#    volumes:
#      - qdrant-data:/qdrant/storage
#    ports:
#      - "6333:6333"
#    healthcheck:
#      test: ["CMD", "wget", "-qO-", "http://localhost:6333/ready"]
#      interval: 10s
#      timeout: 3s
#      retries: 5
#    networks: [internal]

  minio:
    image: minio/minio:latest
    container_name: df_minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER= forge
      - MINIO_ROOT_PASSWORD= forge123
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9000/minio/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [internal]
  
  api-gateway:
    build:
      context: ../Services/api-gateway
      dockerfile: Dockerfile
    container_name: df_api
    restart: always
    working_dir: /app          # <- ajuste conforme teu Dockerfile copia (ex: COPY . /app)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8020:8000"
    env_file:
      - ../Services/api-gateway/.env
    depends_on:
      - postgres
    #  - redis
    #  - qdrant
      - minio
    networks: [internal]
    volumes:
      - ../Services/api-gateway:/app


networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
  qdrant-data:
  minio-data:
